services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  backend:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229" # for debugging
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
    command: npm run start:dev
    depends_on:
      redis:
        condition: service_healthy
  