services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      REDIS_HOST: redis
    command: npm run start:dev
  redis:
    image: redis:latest
    ports:
      - "6379:6379"